import type { Metadata, Viewport } from 'next'
import { GeistSans } from 'geist/font/sans'

import { cn } from '@/lib/utils'
import { ProvidersTree } from '@/components/providers/providers-tree'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' },
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'bg-background font-sans antialiased',
          GeistSans.variable
        )}
      >
        <ProvidersTree>{children}</ProvidersTree>
      </body>
    </html>
  )
}
