import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'

import { cn } from '@/lib/utils'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'bg-background font-sans antialiased',
          GeistSans.variable
        )}
      >
        {children}
      </body>
    </html>
  )
}
